# Generated by Django 5.2.11 on 2026-04-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pais_origem', models.CharField(max_length=80)),
                ('ano_fundacao', models.PositiveIntegerField()),
                ('motor', models.CharField(max_length=80)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
