# Generated by Django 5.2.11 on 2026-05-15 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tututuru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=80)),
                ('extensao_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('numero_curvas', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Circuito',
                'verbose_name_plural': 'Circuitos',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'ordering': ['nome'], 'verbose_name': 'Equipe', 'verbose_name_plural': 'Equipes'},
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('data', models.DateField()),
                ('temporada', models.PositiveIntegerField()),
                ('total_voltas', models.PositiveSmallIntegerField()),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas', to='tututuru.circuito')),
            ],
            options={
                'verbose_name': 'Corrida',
                'verbose_name_plural': 'Corridas',
                'ordering': ['-data', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nacionalidade', models.CharField(max_length=60)),
                ('data_nascimento', models.DateField()),
                ('numero_largada', models.PositiveSmallIntegerField()),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilotos', to='tututuru.equipe')),
            ],
            options={
                'verbose_name': 'Piloto',
                'verbose_name_plural': 'Pilotos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=80)),
                ('ano', models.PositiveIntegerField()),
                ('numero_carro', models.PositiveSmallIntegerField()),
                ('chassi', models.CharField(max_length=80)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carros', to='tututuru.equipe')),
                ('piloto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carro', to='tututuru.piloto')),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['modelo', 'numero_carro'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoCorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao_largada', models.PositiveSmallIntegerField()),
                ('posicao_final', models.PositiveSmallIntegerField()),
                ('voltas_completadas', models.PositiveSmallIntegerField()),
                ('tempo_total', models.DurationField()),
                ('melhor_volta', models.DurationField()),
                ('pontos_obtidos', models.PositiveSmallIntegerField()),
                ('status', models.CharField(max_length=40)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='tututuru.carro')),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='tututuru.corrida')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='tututuru.piloto')),
            ],
            options={
                'verbose_name': 'Resultado da Corrida',
                'verbose_name_plural': 'Resultados das Corridas',
                'ordering': ['corrida', 'posicao_final'],
            },
        ),
    ]
